### PR TITLE
Added about page [Issue #33]

### PR DESCRIPTION
**Pull request by roysammy**
Have added the About Us page for the website as proposed in [Issue #33](https://github.com/Abidsyed25/ScrapQuest/issues/33)

Here is a video of how the about us page looks:

https://github.com/Abidsyed25/ScrapQuest/assets/78533174/f552a5c6-8637-4894-8dcd-c8794910d037

Please review and merge @Abidsyed25

### CODE REVIEW

**Comment by Abidsyed25** [comment]
@roysammy123 please resolve merge conflicts.

**Comment by roysammy** [comment]
@Abidsyed25 resolved the conflict, please check and merge now

**Comment by Abidsyed25** [comment]
hi @roysammy123, checkout preview of PR here - [here](https://quine-scrap-quest-1p585s18a-abidsyed25s-projects.vercel.app/). Maybe because of merge conflicts it is not properly integrated onto the website.

**Comment by Abidsyed25** [comment]
My suggestion is to add about page link in the footer bar.

**Comment by roysammy** [comment]
@Abidsyed25  Hi, I will add the contact page link when I raise PR for the [nav menu issue](https://github.com/Abidsyed25/ScrapQuest/issues/50). Then it will get visible

**Comment by Abidsyed25** [comment]
@roysammy123 I am still getting merge conflicts. Please open a new PR with the present source code.

**Pull request closed without merging**
