### PR TITLE
Enhanced the FAQ page

### LINKED ISSUE #209: 💡[FEATURE]: To enhance the FAQ page
To enhance the FAQ page

### PR DESCRIPTION
**Pull request by ayush-848**
# Description
- Changed background
- Restyled the coloring of the accordion
- Make the accordion content differentiable
- Added hover effects
Fixes:  #209

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image

### CODE REVIEW

**Comment by ayush-848** [comment]
@Abidsyed25 please check it

**Comment by ayush-848** [comment]
@Abidsyed25 please check this pr

**Comment by ayush-848** [comment]
@Abidsyed25 is there any problem in this???

**Comment by Abidsyed25** [comment]
@ayush-848 I am getting errors

**Comment by Abidsyed25** [comment]
@ayush-848 please resolve the errors

**Comment by ayush-848** [comment]
> @ayush-848 please resolve the errors

@Abidsyed25 can you give me the error screenshots??
I cannot find any info

**Comment by Abidsyed25** [comment]
@ayush-848 I have pasted error below
 Failed to compile.
./app/faq/page.tsx:28:42
Type error: Type '{ children: Element[]; type: "multiple"; collapsible: true; className: string; }' is not assignable to type 'IntrinsicAttributes & ((AccordionSingleProps | AccordionMultipleProps) & RefAttributes<HTMLDivElement>)'.
  Property 'collapsible' does not exist on type 'IntrinsicAttributes & AccordionMultipleProps & RefAttributes<HTMLDivElement>'.
  26 |           <div className="flex flex-col items-center justify-center">
  27 |             <div style={{ width: "750px" }}>
> 28 |               <Accordion type="multiple" collapsible className="w-full">
     |                                          ^
  29 |                 {faqs.map((faq, index) => (
  30 |                   <AccordionItem key={index} value={`item-${index}`} className="my-4">
  31 |                     <AccordionTrigger className="accordion-trigger">
Error: Command "npm run build" exited with 1

**Comment by ayush-848** [comment]
> @ayush-848 I have pasted error below Failed to compile. ./app/faq/page.tsx:28:42 Type error: Type '{ children: Element[]; type: "multiple"; collapsible: true; className: string; }' is not assignable to type 'IntrinsicAttributes & ((AccordionSingleProps | AccordionMultipleProps) & RefAttributes)'. Property 'collapsible' does not exist on type 'IntrinsicAttributes & AccordionMultipleProps & RefAttributes'. 26 |
> 
> 
> 27 | <div style={{ width: "750px" }}>
> > 28 |               
> > |                                          ^
> > 29 |                 {faqs.map((faq, index) => (
> > 30 |                   <AccordionItem key={index} value={`item-${index}`} className="my-4">
> > 31 |                     
> > Error: Command "npm run build" exited with 1

ok let me fix it
give me few minutes

**Comment by ayush-848** [comment]
@Abidsyed25 now see

**Comment by ayush-848** [comment]
@Abidsyed25 now is it fixed ???????

**Comment by MastanSayyad** [comment]
@ayush-848 @Abidsyed25 May I know why this PR has level 3 as i can see only accordion answer theme has been changed + css code formatting, 




These are the only changes made by the contributor 

on the other hand PR #196 which has more enhancements and functionalities has level 2.

Can you pls explain it?

**Comment by ayush-848** [comment]
> @ayush-848 @Abidsyed25 May I know why this PR has level 3 as i can see only accordion answer theme has been changed + css code formatting,
> 
> 
> 
> These are the only changes made by the contributor
> 
> on the other hand PR #196 which has more enhancements and functionalities has level 2.
> 
> Can you pls explain it?

@MastanSayyad For the issue I did some coloring and positioning part and the level was purely assigned by the admin

**Comment by MastanSayyad** [comment]
Yes @ayush-848 I'm asking the admin only, as I have been instructed if the page is not created by the Contributor and has only Enhancement then it should be level 1 or level 2, 

The difference between the PR #196 and yours is what made me curious.

If you have re-created the entire FAQ page or did any functionality additions (complex one)  then the level 3 label is understandable!

 I'm just asking as the previous PR has level 2 but as compare to the changes this PR has level 3. So Just for clarification. So that when the gssoc team Reviews your profile they shoud not question you!

**Comment by ayush-848** [comment]
> Yes @ayush-848 I'm asking the admin only, as I have been instructed if the page is not created by the Contributor and has only Enhancement then it should be level 1 or level 2,
> 
> The difference between the PR #196 and yours is what made me curious.
> 
> If you have re-created the entire FAQ page or did any functionality additions (complex one) then the level 3 label is understandable!
> 
> I'm just asking as the previous PR has level 2 but as compare to the changes this PR has level 3. So Just for clarification. So that when the gssoc team Reviews your profile they shoud not question you!

Yeah compared to #196 this was not that much of a change

**Pull request merged**
