### PR TITLE
added workflow for closing old issues

### LINKED ISSUE #45: 💡[FEATURE]: Workflow for Closing Old Issues
**Is your feature request related to a problem? Please describe.**
Over time, repositories can accumulate a large number of open issues, including some that may no longer be relevant or actively worked on. Manually closing these old issues can be time-consuming and tedious.

**Describe the solution you'd like**
I would like a workflow that automatically identifies and closes old issues based on certain criteria, such as no recent activity or being open for a specific duration.

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #45 

@kartikayasijaa please review and merge this PR

Also, add labels to this PR

### CODE REVIEW

**Comment by Abidsyed25** [comment]
@Asymtode712 Increase the time limit for closing issues. I think there is only 30 days limit specified in code, increase it to 6 months.

**Comment by Asymtode712** [comment]
@Abidsyed25 as you say

**Comment by Asymtode712** [comment]
@Abidsyed25 done with the changes

**Comment by Asymtode712** [comment]
@thekumbhaj please add the labels and assign me this PR

Thank you!

**Pull request merged**
