### PR TITLE
Completed footer component

### LINKED ISSUE #59: 💡[FEATURE]:  Footer for the website
**Is your feature request related to a problem? Please describe.**
This website needs a footer with a copyright icon and year.

### PR DESCRIPTION
**Pull request by gdhyani**
# Description

Footer component with copywrite and year

Fixes:  #59

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [ ] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Abidsyed25** [comment]
@gdhyani its not visible. Try to change background color

**Comment by gdhyani** [comment]
What colour do you want.
I choose to keep it simple as it only contains copyright.

**Comment by Abidsyed25** [comment]
@gdhyani Hey, you can also change text color instead of background-color. Because the text is invisible on the website.

**Comment by gdhyani** [comment]
sir you closed the request. I have changed opacity of footer for better text visibility.

**Comment by gdhyani** [comment]
Can i reopen and push the new code.

**Comment by Abidsyed25** [comment]
@gdhyani looks better now

**Pull request merged**
