### PR TITLE
Adding Home Icon to every Page

### LINKED ISSUE #147: 💡[FEATURE]:  Adding Home icon
**Is your feature request related to a problem? Please describe.**
@Abidsyed25 I want to add home icon to all the pages so that by clicking on it , it can go back to the main home page. Kindly assign this issue to me.

**Describe the solution you'd like**
N.A
**Describe alternatives you've considered**
N.A

**Additional context**
N.A

### PR DESCRIPTION
**Pull request by Ojas-Arora**
# Description

@Abidsyed25 I have added the home icon to every page and also improved the styling in some pages. Kindly review this.

Fixes:  #147 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Abidsyed25** [comment]
@Ojas-Arora few checks have been failed. Please try to resolve that and also resolve merge conflicts

**Comment by Abidsyed25** [comment]
@Ojas-Arora try to add a video of what changes you exactly made on this website

**Comment by Ojas-Arora** [comment]
@Abidsyed25 ok

**Comment by Ojas-Arora** [comment]
@Abidsyed25 I have resolved all the conflicts and I don't know how to make video but I can tell u what changes I have made
Added Home Icon png in all the pages i.e about us,FAQ,Terms and Conditions and Contact Page.
Linked the home icon in all the pages i.e about us,FAQ,Terms and Conditions and Contact Page.
Improved the styling in these pages also.
Kindly review this.

**Pull request merged**
