### PR TITLE
Fixes #35

### LINKED ISSUE #35: Reduce API response time for puppeteer service
It looks like the service is taking longer to respond than what's allowed in the free tier of Vercel Functions, resulting in a `timeout` error. To address this, we'll need to make some changes to the architecture. If anyone is interested in this issue, please reach out to me so we can discuss the approach.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
@kartikayasijaa Reduced the time taken for the service to respond from 24.6s to 3.9s.

Fixes #35 

Before:

Screenshot 2024-05-21 011708

After:

Screenshot 2024-05-21 012035

### CODE REVIEW

**Comment by Sambit-Mondal** [comment]
@kartikayasijaa I beg pardon that I mistakenly tried to deploy it. Kindly review it.

**Comment by kartikay-tsds** [comment]
@Sambit-Mondal I don't see any major change in response time. It is still the same.

**Comment by kartikayasijaa** [comment]
@Sambit-Mondal  I don't see any major change in response time. It is still the same.

**Comment by Sambit-Mondal** [comment]
@kartikayasijaa Ohh! But it worked for me yesterday. Don't know then :)

**Pull request closed without merging**
