### PR TITLE
enhanced the about us page

### LINKED ISSUE #220: 💡[FEATURE]: To enhance the about page
To enhance the about page

### PR DESCRIPTION
**Pull request by ayush-848**
Fixes:  #220

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image

### CODE REVIEW

**Comment by ayush-848** [comment]
@Abidsyed25 check it please

**Comment by ayush-848** [comment]
@Abidsyed25 will you be coming anytime before 7 pm again??

**Comment by ayush-848** [comment]
coz i have one more issue to work on I think I can make a PR before 5

**Comment by Abidsyed25** [comment]
@ayush-848 Nope , I am busy

**Comment by ayush-848** [comment]
> @ayush-848 Nope , I am busy

Sure thanks for being a great mentor

**Pull request merged**
