### PR TITLE
Bug : Fixed Static copyright year

### PR DESCRIPTION
**Pull request by Meetjain1**
### Description:
This PR enhances the footer section of the website by adding the current copyright year, which is fetched dynamically. This ensures that the copyright year will always be up-to-date without requiring manual updates each year.

#### Changes:
1. **Footer HTML**: Updated the footer to include a placeholder for the copyright year.
2. **JavaScript**: Added a script to fetch the current year dynamically and insert it into the footer.
3. **CSS**: Ensured that the styling of the footer remains consistent with the new dynamic content.

#### Benefits:
- **Automation**: The copyright year updates automatically, reducing maintenance overhead.
- **Accuracy**: Ensures the displayed year is always current, improving the website's professionalism.

Fixes:  #(issue no.)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [ ] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Abidsyed25** [comment]
@Meetjain1 Issue was created by [Tejashri-Taral](https://github.com/Tejashri-Taral) ?? #189

**Comment by Meetjain1** [comment]
> @Meetjain1 Issue was created by [Tejashri-Taral](https://github.com/Tejashri-Taral) ?? #189

@Abidsyed25 extremely sorry for this I didnt look the issue is already there , [Tejashri-Taral](https://github.com/Tejashri-Taral) Are u working on this ?

**Comment by Tejashri-Taral** [comment]
@Meetjain1, yes I'm working on it

**Comment by Meetjain1** [comment]
Ok ,closing this pr @Abidsyed25 @Tejashri-Taral . I am Sorry for this .

**Pull request closed without merging**
