### PR TITLE
updated main page

### PR DESCRIPTION
**Pull request by YadlaMani**
Added better styling to the home page
image

### CODE REVIEW

**Comment by YadlaMani** [comment]
closes #25 @Abidsyed25 review the pr

**Comment by Abidsyed25** [comment]
quine-scrap-quest-git-fork-yadlamani-main-abidsyed25s-projects vercel app_
@YadlaMani  The background has not changed. check it once.

**Comment by YadlaMani** [comment]
@Abidsyed25 i only changed some aspects should I change background too any suggestions

**Comment by Abidsyed25** [comment]
@YadlaMani yeah, the background of your screenshot is different from your pull request code. Check it once.
Here is preview link of your PR - https://quine-scrap-quest-git-fork-yadlamani-main-abidsyed25s-projects.vercel.app/

**Comment by YadlaMani** [comment]
I use dark mode @Abidsyed25 so it's like that I didn't change background

**Comment by Abidsyed25** [comment]
@YadlaMani yeah change background too. The present background doesnot suited for the navbar color. Dark background is recommended

**Comment by YadlaMani** [comment]
@Abidsyed25 okay

**Comment by YadlaMani** [comment]
@Abidsyed25 yeah done the changes

**Pull request merged**
